name: Deploy App to Firebase Hosting

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Client
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: .
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPIDR_CHALLENGE }}
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT }}